# Set global labels and annotations to be used across all objects created by the chart
global:
  labels: {}
  annotations: {}

mariadb:
  enabled: false

apps:
  nginx:
    enabled: true
    type: deployment
    replicas: 1
    image:
      repository: nginx
      tag: latest
      pullPolicy:
    command: []
    args: []
    env:
    envFrom: []
    volumeMounts: []
    annotations: {}
    labels: {}
    automountServiceAccountToken: true
    serviceAccount:
      # the underlying templates here are currently broken
      create: false
      #annotations: {}
      #name: "vaultwarden-sa"
    strategy:
    rollingUpdate:
      unavailable:
      surge:
      partition:
    revisionHistoryLimit: 3
    probes:
      liveness:
        enabled: false
      readiness:
        enabled: false
      startup:
        enabled: false
    termination:
      messagePath:
      messagePolicy:
      gracePeriodSeconds:


  vaultwarden:
    enabled: true
    type: deployment
    replicas: 1
    image:
      repository: vaultwarden/server
      tag: 1.27.0-alpine
      pullPolicy:
    command: []
    args: []
    env:
    envFrom: []
    volumeMounts: []
    annotations: {}
    labels: {}
    automountServiceAccountToken: true
    serviceAccount:
      # the underlying templates here are currently broken
      create: false
      #annotations: {}
      #name: "vaultwarden-sa"
    strategy:
    rollingUpdate:
      unavailable:
      surge:
      partition:
    revisionHistoryLimit: 3
    probes:
      liveness:
        enabled: false
      readiness:
        enabled: false
      startup:
        enabled: false
    termination:
      messagePath:
      messagePolicy:
      gracePeriodSeconds:

services:
  example:
    enabled: false
    nameOverride:
    type: ClusterIP
    externalTrafficPolicy:
    ipFamilyPolicy:
    ipFamilies: []
    annotations: {}
    labels: {}
    ports:
      http:
        enabled: true
        primary: true
        port:
        protocol: HTTP
        targetPort:
        nodePort:
