# Set global labels and annotations to be used across all objects created by the chart
global:
  labels: {}
  annotations: {}

mariadb:
  enabled: false

apps:
  vaultwarden:
    enabled: true
    type: deployment
    replicas: 1
    image:
      repository: vaultwarden/server
      tag: 1.27.0-alpine

services:
  vaultwarden:
    enabled: true
    appName: vaultwarden
    type: ClusterIP
    ports:
      http:
        enabled: true
        port: 80
        protocol: HTTP
        targetPort: 80

ingresses:
  vaultwarden:
    enabled: true
    serviceName: vaultwarden
    ## Configure the hosts for the ingress
    hosts:
      - host: vaultwarden.example.com
        paths:
          - path: /
            pathType: Prefix
            service:
              port: 80
    tls: []
