# Set global labels and annotations to be used across all objects created by the chart
global:
  labels: {}
  annotations: {}

mariadb:
  enabled: false

apps:
  nginx:
    enabled: true
    type: deployment
    replicas: 1
    image:
      repository: nginx
      tag: latest

  vaultwarden:
    enabled: true
    type: deployment
    replicas: 1
    image:
      repository: vaultwarden/server
      tag: 1.27.0-alpine

services:
  nginx:
    enabled: true
    appName: nginx
    type: ClusterIP
    ports:
      http:
        enabled: true
        port: 80
        protocol: HTTP
        targetPort: 80

  vaultwarden:
    enabled: true
    appName: vaultwarden
    type: ClusterIP
    ports:
      http:
        enabled: true
        port: 80
        protocol: HTTP
        targetPort: 80
