#
# IMPORTANT NOTE
#
# This chart inherits from our replicated library chart.
# https://github.com/replicatedhq/replicated-library-chart


# Enables the main service. Sets type to Deployment
main:
  enabled: true
  type: "deployment"

# Main service image
image:
  # -- image repository
  repository: nginx
  # -- image tag
  tag: latest
  # -- image pull policy
  pullPolicy: IfNotPresent

# Main service's service
service:
  main:
    primary: true
    ports:
      http:
        port: 80

# -- Configure persistence settings for the chart under this key.
persistence:
  main:
    enabled: true
    mountPath: /usr/share/nginx/html/
    type: "configMap"

# -- Configure configMap settings for the chart under this key.
configmap:
  main: 
    enabled: true
    data:
      index.html: |
        <!doctype html>
        <html>
          <head>
            <meta http-equiv="Content-Type" content="text/html; charset=utf-8"/>
            <title>Demo Application</title>
            <link href="styles.css" rel="stylesheet" type="text/css">
          </head>
          <body>
            This is an example KOTS application.
            <p>This is text from a user config value: '{{repl ConfigOption "example_default_value"}}' </p>
            </br>
            This is a hidden value: '{{repl ConfigOption "hidden_text"}}'
          </body>
        </html>
      styles.css: |
        body {
          text-align: center;
          background-color: rgb(224,224,224);
          font-family: Verdana, Arial, Helvetica, sans-serif;
          font-size: 100%;
        }

ingress:
# -- Enable and configure ingress settings for the chart under this key.
  main:
    enabled: false
