---
apiVersion: kots.io/v1beta1
kind: Application
metadata:
  name: vaultwarden
spec:
  title: Vaultwarden
  icon: https://raw.githubusercontent.com/cncf/artwork/master/projects/kubernetes/icon/color/kubernetes-icon-color.png
  statusInformers:
    - deployment/vaultwarden
  ports:
    - serviceName: "vaultwarden"
      servicePort: 80
      localPort: 80
      applicationUrl: "http://vaultwarden"
